### ISSUE TITLE
[eqf/eqf_option_ext_error] displayed when incorrect file extension entered.

### ISSUE THREAD

**Issue by drew1two** [Jacksiro/Q2A-Extra-Question-Field-Plugin#1]
Seems not to be replaced by text in the Lang files.

Same when editing a question...
[eqf/extra_field_remove] is displayed instead of "remove"

**Comment by JacksiroKe** [comment]
Sorry @drew1two i have been busy but i will check why you are getting such an error.

Kindly give full details on how to reproduce the error

**Comment by JacksiroKe** [comment]
I will close because user did not give full details as requested
